[project]
name = "projeto-consumomensal-automacaodecompras"
version = "0.1.0"
description = ""
authors = [
    {name = "João Gabriel Da Silva",email = "jgs.officiall@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.2,<4.0.0)",
    "ipykernel (>=7.2.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "projeto_consumomensal_automacaodecompras", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)"
]
